#!/bin/sh


/sbin/ldconfig
   
cat > /etc/init.d/clos <<EOF
#!/bin/sh

# mm at nisu.org 2004
# modified by psn 2006 
# use at your own risk

# chkconfig: 2345 95 20
# description: Clauer Os Service
# processname: clos


### BEGIN INIT INFO
# Provides:             defaultdaemon
# Required-Start:       $local_fs $network
# Required-Stop:        $local_fs $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start daemon at boot time
# Description:Enable service provided by daemon.
### END INIT INFO


case "\$1" in
    start)
        echo  "Starting clos ..."
	if [ ! X"\$(pidof clos)" = X"" ]
	  then
	    echo "clos is already running, try doing clos restart"
	    exit 1
	fi
	
        $1/clos

	if [ ! X"\$(pidof clos)" = X"" ]
           then
              echo "clos started successfully"
              exit 0
        fi
        ;;
    stop)
	echo  "Stopping clos ..."
	if [ ! X"\$(pidof clos)" = X"" ]
	   then 
	       kill \$(pidof clos)
	   else 
	       echo "It seems like clos is not running"
	fi
	;;
    restart)
	echo  "Stopping clos ..."
        if [ ! X"\$(pidof clos)" = X"" ]
           then
               kill \$(pidof clos)
           else
               echo "It seems like clos is not running"
        fi
	sleep 1
	echo  "Starting clos ..."
	
	$1/clos

        if [ ! X"\$(pidof clos)" = X"" ]
           then
              echo "clos started successfully"
              exit 0
        fi
 	;;
    *)
        echo "Usage: \$0 {start|stop|restart}"
        exit 1
	;;
esac
EOF


chmod u+x /etc/init.d/clos 


pers=1
if [ -f "/home/clauer/pers" ]
then
        pers=$(cat /home/clauer/pers)
fi 

cat > /etc/clos.conf <<EOF
#
# Configuration file for clos
# Universitat Jaume I
#

#version of the clauer software
version= 3.0.6
type= $pers
EOF

chmod u+x /etc/init.d/clos

if [ -f /etc/SuSE-release ]
then 
	insserv -d /etc/init.d/clos
elif [ -f /etc/redhat-release ]
then
	chkconfig --add clos
else
    if [ "$(which update-rc.d)" ]
    then 
	update-rc.d clos defaults
    else 
	echo "No puedo actualizar los rc, deberas hacerlo de forma manual."
    fi
fi

if (( $? != 0 ))
then 
   echo "Sucedio un error actualizando los niveles rc, deberás instalarlo manualmente"
fi
